tgstation-github-automation-tools: TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule Class Reference
TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule Class Reference
Generates changelog .yaml files
Public Member Functions
IEnumerable< IPayloadHandler< TPayload > > GetPayloadHandlers< TPayload > ()
The IPayloadHandler<TPayload>s the IComponentProvider contains
ChangelogGeneratorModule (IDataStoreFactory< ChangelogGeneratorModule > dataStoreFactory, IStringLocalizer< ChangelogGeneratorModule > stringLocalizer, IOptions< GeneralConfiguration > generalConfigurationOptions, IIOManager ioManager, IRepository repository)
Construct a ChangelogGeneratorModule
Task Initialize (CancellationToken cancellationToken)
Load components in the IComponentProvider. Will be called before any other function
Task AddViewVars (PullRequest pullRequest, dynamic viewBag, CancellationToken cancellationToken)
Adds vars to the Microsoft.AspNetCore.Mvc.Controller.ViewBag of the Controllers.PullRequestController
async Task< AutoMergeStatus > EvaluateFor (PullRequest pullRequest, CancellationToken cancellationToken)
Run the IMergeRequirement for a given pullRequest
async Task< string > ModifyMerge (PullRequest pullRequest, string workingCommit, CancellationToken cancellationToken)
Modify a pullRequest
Public Attributes
Guid Uid => new Guid("eb442717-57a2-402f-bfd4-0d4dce80f16a")
string Name => "Changelog Generator"
string Description => "Generates .yaml changelog files"
IEnumerable< IMergeRequirement > MergeRequirements => Enumerable.Empty<IMergeRequirement>()
IEnumerable< IMergeHook > MergeHooks => new List<IMergeHook> { this }
Properties
bool Enabled [get, set]
Properties inherited from TGWebhooks.Modules.IModule
bool Enabled [set]
If the IModule is enabled
Guid Uid [get]
A unique Uid for the IModule
string Name [get]
The name of the IModule
string Description [get]
A verbose user-friendly description of the IModule
Properties inherited from TGWebhooks.Modules.IComponentProvider
IEnumerable< IMergeRequirement > MergeRequirements [get]
The IMergeRequirements the IComponentProvider contains
IEnumerable< IMergeHook > MergeHooks [get]
The IMergeHooks the IComponentProvider contains
Private Attributes
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the ChangelogGeneratorModule
readonly IDataStore dataStore
The IDataStore for the ChangelogGeneratorModule
readonly IStringLocalizer< ChangelogGeneratorModule > stringLocalizer
The IStringLocalizer for the ChangelogGeneratorModule
readonly IIOManager ioManager
The IIOManager for the ChangelogGeneratorModule
readonly IRepository repository
The IRepository for the ChangelogGeneratorModule
Detailed Description
Generates changelog .yaml files
Definition at line 20 of file ChangelogGeneratorModule.cs.
Constructor & Destructor Documentation
TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.ChangelogGeneratorModule (IDataStoreFactory< ChangelogGeneratorModule > dataStoreFactory, IStringLocalizer< ChangelogGeneratorModule > stringLocalizer, IOptions< GeneralConfiguration > generalConfigurationOptions, IIOManager ioManager, IRepository repository)
Construct a ChangelogGeneratorModule
Parameters
dataStoreFactory The IDataStoreFactory<TModule> to create dataStore from
stringLocalizer The value of stringLocalizer
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration
ioManager The value of ioManager
repository The value of repository
Definition at line 71 of file ChangelogGeneratorModule.cs.
References TGWebhooks.Modules.IDataStoreFactory< TModule >.CreateDataStore().
         {
             this.stringLocalizer = stringLocalizer ?? throw new ArgumentNullException(nameof(stringLocalizer));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
             generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
             dataStore = dataStoreFactory?.CreateDataStore(this) ?? throw new ArgumentNullException(nameof(dataStoreFactory));
         }
Member Function Documentation
Task TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.AddViewVars (PullRequest pullRequest, dynamic viewBag, CancellationToken cancellationToken)
Adds vars to the Microsoft.AspNetCore.Mvc.Controller.ViewBag of the Controllers.PullRequestController
Implements TGWebhooks.Modules.IComponentProvider.
async Task<AutoMergeStatus> TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.EvaluateFor (PullRequest pullRequest, CancellationToken cancellationToken)
Run the IMergeRequirement for a given pullRequest
Implements TGWebhooks.Modules.IMergeRequirement.
Definition at line 87 of file ChangelogGeneratorModule.cs.
References TGWebhooks.Models.Changelog.GetChangelog(), and TGWebhooks.Modules.AutoMergeStatus.Notes.
         {
             if (pullRequest == null)
                 throw new ArgumentNullException(nameof(pullRequest));
             var setRequired = await dataStore.ReadData<RequireChangelogEntry>(pullRequest.Number.ToString(), cancellationToken).ConfigureAwait(false);
             if (!setRequired.Required.HasValue)
                 setRequired.Required = generalConfiguration.DefaultChangelogRequired;
             var changelog = Changelog.GetChangelog(pullRequest, out bool malformed);
             var result = new AutoMergeStatus
             {
                 FailStatusReport = true,
                 RequiredProgress = 2, //setRequired.Required.Value || malformed ? 1 : 0, //TODO:maintainer_can_modify field
                 Progress = (changelog != null ? 1 : 0)
             };
             if (result.Progress < result.RequiredProgress || malformed)
                 result.Notes.Add(stringLocalizer[malformed ? "ChangelogMalformed" : "NeedsChangelog"]);
             return result;
         }
IEnumerable<IPayloadHandler<TPayload> > TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.GetPayloadHandlers< TPayload > ()
The IPayloadHandler<TPayload>s the IComponentProvider contains
Implements TGWebhooks.Modules.IComponentProvider.
Type Constraints
TPayload : ActivityPayload
TPayload : Enumerable.Empty
TPayload : IPayloadHandler<TPayload>
Task TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.Initialize (CancellationToken cancellationToken)
Load components in the IComponentProvider. Will be called before any other function
Implements TGWebhooks.Modules.IInitializable.
async Task<string> TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.ModifyMerge (PullRequest pullRequest, string workingCommit, CancellationToken cancellationToken)
Modify a pullRequest
Implements TGWebhooks.Modules.IMergeHook.
Definition at line 111 of file ChangelogGeneratorModule.cs.
References TGWebhooks.Models.Changelog.GetChangelog().
         {
             if (pullRequest == null)
                 throw new ArgumentNullException(nameof(pullRequest));
             if (workingCommit == null)
                 throw new ArgumentNullException(nameof(workingCommit));
             var changelog = Changelog.GetChangelog(pullRequest, out bool malformed);
             if (changelog == null)
                 return workingCommit;
             var result = new List<Dictionary<string, string>>();
             result.AddRange(changelog.Changes.Select(x => new Dictionary<string, string> { { x.Type.ToString().ToLowerInvariant(), x.Text } }));
             //create the object graph
             var graph = new
             {
                 author = changelog.Author,
                 delete_after_temporary_for_replacement = true,
                 changes = result
             };
             //hack because '-' isn't a valid identifier in c#
             var yaml = new Serializer().Serialize(graph).Replace("delete_after_temporary_for_replacement", "delete-after");
             var title = String.Format(CultureInfo.InvariantCulture, "AutoChangeLog-pr-{0}.yml", pullRequest.Number);
             var pathToWrite = ioManager.ConcatPath(repository.Path, "html", "changelogs", title);
             await ioManager.WriteAllText(pathToWrite, yaml, cancellationToken).ConfigureAwait(false);
             return await repository.CommitChanges(new List<string> { pathToWrite }, cancellationToken);
         }
Member Data Documentation
readonly IDataStore TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.dataStore private
The IDataStore for the ChangelogGeneratorModule
Definition at line 49 of file ChangelogGeneratorModule.cs.
string TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.Description => "Generates .yaml changelog files"
Definition at line 32 of file ChangelogGeneratorModule.cs.
readonly GeneralConfiguration TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.generalConfiguration private
The GeneralConfiguration for the ChangelogGeneratorModule
Definition at line 45 of file ChangelogGeneratorModule.cs.
readonly IIOManager TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.ioManager private
The IIOManager for the ChangelogGeneratorModule
Definition at line 57 of file ChangelogGeneratorModule.cs.
IEnumerable<IMergeHook> TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.MergeHooks => new List<IMergeHook> { this }
Definition at line 38 of file ChangelogGeneratorModule.cs.
IEnumerable<IMergeRequirement> TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.MergeRequirements => Enumerable.Empty<IMergeRequirement>()
Definition at line 35 of file ChangelogGeneratorModule.cs.
string TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.Name => "Changelog Generator"
Definition at line 29 of file ChangelogGeneratorModule.cs.
readonly IRepository TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.repository private
The IRepository for the ChangelogGeneratorModule
Definition at line 61 of file ChangelogGeneratorModule.cs.
readonly IStringLocalizer<ChangelogGeneratorModule> TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.stringLocalizer private
The IStringLocalizer for the ChangelogGeneratorModule
Definition at line 53 of file ChangelogGeneratorModule.cs.
Guid TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.Uid => new Guid("eb442717-57a2-402f-bfd4-0d4dce80f16a")
Definition at line 26 of file ChangelogGeneratorModule.cs.
Property Documentation
bool TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.Enabled get set
Definition at line 23 of file ChangelogGeneratorModule.cs.
The documentation for this class was generated from the following file:
TGWebhooks/Modules/ChangelogGenerator/ChangelogGeneratorModule.cs