tgstation-github-automation-tools: TGWebhooks.Models.Changelog Class Reference
TGWebhooks.Models.Changelog Class Reference
Represents a changelog in the body of a PullRequest
Static Public Member Functions
static Changelog GetChangelog (PullRequest pullRequest, out bool malformed)
Public Attributes
string Author => author
The titled author(s) of the Changelog
IReadOnlyList< ChangelogEntry > Changes => changes
The ChangelogEntrys in the Changelog
Private Member Functions
Changelog (string author, List< ChangelogEntry > changes)
Construct a Changelog
Private Attributes
readonly string author
Backing field for Author
readonly List< ChangelogEntry > changes
Backing field for Changes
Detailed Description
Represents a changelog in the body of a PullRequest
Definition at line 11 of file Changelog.cs.
Constructor & Destructor Documentation
TGWebhooks.Models.Changelog.Changelog (string author, List< ChangelogEntry > changes) private
Construct a Changelog
Parameters
author The value of Author
changes The value of Changes
Definition at line 146 of file Changelog.cs.
         {
             this.author = author;
             this.changes = changes;
         }
Member Function Documentation
static Changelog TGWebhooks.Models.Changelog.GetChangelog (PullRequest pullRequest, out bool malformed) static
Definition at line 31 of file Changelog.cs.
Referenced by TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.EvaluateFor(), TGWebhooks.Modules.ChangelogGenerator.ChangelogGeneratorModule.ModifyMerge(), and TGWebhooks.Modules.PRTagger.PullRequestLabellerModule.TagPR().
         {
             string author = null;
             List<ChangelogEntry> entries = null;
             foreach (var line in pullRequest?.Body?.Split('\n') ?? throw new ArgumentNullException(nameof(pullRequest)))
             {
                 if (String.IsNullOrWhiteSpace(line))
                     continue;
                 var foundTag = line.StartsWith(":cl:") || line.StartsWith("🆑");
                 if (author == null)
                 {
                     if (foundTag)
                     {
                         author = line.Replace(":cl:", String.Empty).Replace("🆑", String.Empty).Trim();
                         if (String.IsNullOrWhiteSpace(author) || author == "optional name here")
                             author = pullRequest.User.Login;
                         entries = new List<ChangelogEntry>();
                     }
                     continue;
                 }
                 if (foundTag)
                 {
                     if (entries.Count == 0)
                     {
                         malformed = true;
                         return null;
                     }
                     malformed = false;
                     return new Changelog(author, entries);
                 }
                 var firstColon = line.IndexOf(':');
                 if (firstColon == -1)
                 {
                     malformed = true;
                     return null;
                 }
                 var header = line.Substring(0, firstColon).ToLowerInvariant();
                 var body = line.Substring(firstColon + 1, line.Length - firstColon - 1).Trim();
                 ChangelogEntryType entryType;
                 switch (header)
                 {
                     case "fix":
                     case "fixes":
                     case "bugfix":
                         entryType = ChangelogEntryType.BugFix;
                         break;
                     case "rsctweak":
                     case "tweaks":
                     case "tweak":
                         entryType = ChangelogEntryType.Tweak;
                         break;
                     case "soundadd":
                         entryType = ChangelogEntryType.SoundAdd;
                         break;
                     case "sounddel":
                         entryType = ChangelogEntryType.SoundDel;
                         break;
                     case "add":
                     case "adds":
                     case "rscadd":
                         entryType = ChangelogEntryType.RscAdd;
                         break;
                     case "imageadd":
                         entryType = ChangelogEntryType.ImageAdd;
                         break;
                     case "imagedel":
                         entryType = ChangelogEntryType.ImageDel;
                         break;
                     case "type":
                     case "spellcheck":
                         entryType = ChangelogEntryType.SpellCheck;
                         break;
                     case "balance":
                     case "rebalance":
                         entryType = ChangelogEntryType.Balance;
                         break;
                     case "code_imp":
                     case "code":
                         entryType = ChangelogEntryType.Code_Imp;
                         break;
                     case "config":
                         entryType = ChangelogEntryType.Config;
                         break;
                     case "admin":
                         entryType = ChangelogEntryType.Admin;
                         break;
                     case "server":
                         entryType = ChangelogEntryType.Server;
                         break;
                     case "refactor":
                         entryType = ChangelogEntryType.Refactor;
                         break;
                     default:
                         //attempt to add it to the last as a new line
                         var last = entries.LastOrDefault();
                         if (last != null)
{
                             entries[entries.Count - 1] = new ChangelogEntry(String.Concat(last.Text, Environment.NewLine, body), last.Type);
                             continue;
                         }
                         malformed = true;
                         return null;
                 }
                 entries.Add(new ChangelogEntry(body, entryType));
             }
             malformed = false;
             return null;
         }
Member Data Documentation
string TGWebhooks.Models.Changelog.Author => author
The titled author(s) of the Changelog
Definition at line 16 of file Changelog.cs.
readonly string TGWebhooks.Models.Changelog.author private
Backing field for Author
Definition at line 25 of file Changelog.cs.
IReadOnlyList<ChangelogEntry> TGWebhooks.Models.Changelog.Changes => changes
The ChangelogEntrys in the Changelog
Definition at line 20 of file Changelog.cs.
readonly List<ChangelogEntry> TGWebhooks.Models.Changelog.changes private
Backing field for Changes
Definition at line 29 of file Changelog.cs.
The documentation for this class was generated from the following file:
TGWebhooks/Models/Changelog.cs