tgstation-github-automation-tools: TGWebhooks.Modules.SemaphoreSlimContext Class Reference
TGWebhooks.Modules.SemaphoreSlimContext Class Reference
Async lock context helper
Public Member Functions
void Dispose ()
Release the lock on lockedSemaphore
Static Public Member Functions
static async Task< SemaphoreSlimContext > Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken)
Asyncronously locks a semaphore
Private Member Functions
SemaphoreSlimContext (SemaphoreSlim _lockedSemaphore)
Construct a SemaphoreSlimContext
~SemaphoreSlimContext ()
Finalize the SemaphoreSlimContext
Private Attributes
SemaphoreSlim lockedSemaphore
The locked SemaphoreSlim
Detailed Description
Async lock context helper
Definition at line 10 of file SemaphoreSlimContext.cs.
Constructor & Destructor Documentation
TGWebhooks.Modules.SemaphoreSlimContext.SemaphoreSlimContext (SemaphoreSlim _lockedSemaphore) private
Construct a SemaphoreSlimContext
Parameters
_lockedSemaphore The value of lockedSemaphore
Definition at line 36 of file SemaphoreSlimContext.cs.
         {
             lockedSemaphore = _lockedSemaphore;
         }
TGWebhooks.Modules.SemaphoreSlimContext.~SemaphoreSlimContext () private
Finalize the SemaphoreSlimContext
Definition at line 44 of file SemaphoreSlimContext.cs.
         {
             Dispose();
         }
Member Function Documentation
void TGWebhooks.Modules.SemaphoreSlimContext.Dispose ()
Release the lock on lockedSemaphore
Definition at line 52 of file SemaphoreSlimContext.cs.
         {
             if (lockedSemaphore == null)
                 return;
             lockedSemaphore.Release();
             lockedSemaphore = null;
             GC.SuppressFinalize(this);
         }
static async Task<SemaphoreSlimContext> TGWebhooks.Modules.SemaphoreSlimContext.Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken) static
Asyncronously locks a semaphore
Parameters
semaphore The SemaphoreSlim to lock
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the SemaphoreSlimContext for the lock
Definition at line 18 of file SemaphoreSlimContext.cs.
Referenced by TGWebhooks.Core.AutoMergeHandler.CheckMergePullRequest(), TGWebhooks.Core.GitHubManager.CheckUser(), TGWebhooks.Core.GitHubManager.GetUserLogin(), and TGWebhooks.Core.ModuleManager.Initialize().
         {
             if (semaphore == null)
                 throw new ArgumentNullException(nameof(semaphore));
             await semaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
             cancellationToken.ThrowIfCancellationRequested();
             return new SemaphoreSlimContext(semaphore);
         }
Member Data Documentation
SemaphoreSlim TGWebhooks.Modules.SemaphoreSlimContext.lockedSemaphore private
The locked SemaphoreSlim
Definition at line 30 of file SemaphoreSlimContext.cs.
The documentation for this class was generated from the following file:
TGWebhooks/Modules/SemaphoreSlimContext.cs