//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGWebhooks.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGWebhooks.Tests.TestObjects", typeof(TestObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 93808093,
        ///    &quot;user&quot;: {
        ///      &quot;login&quot;: &quot;WJohn&quot;,
        ///      &quot;id&quot;: 5988156,
        ///      &quot;avatar_url&quot;: &quot;https://avatars1.githubusercontent.com/u/5988156?v=4&quot;,
        ///      &quot;gravatar_id&quot;: &quot;&quot;,
        ///      &quot;url&quot;: &quot;https://api.github.com/users/WJohn&quot;,
        ///      &quot;html_url&quot;: &quot;https://github.com/WJohn&quot;,
        ///      &quot;followers_url&quot;: &quot;https://api.github.com/users/WJohn/followers&quot;,
        ///      &quot;following_url&quot;: &quot;https://api.github.com/users/WJohn/following{/other_user}&quot;,
        ///      &quot;gists_url&quot;: &quot;https://api.github.com/users/WJohn/gists{/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PR1Changes1Approved {
            get {
                return ResourceManager.GetString("PR1Changes1Approved", resourceCulture);
            }
        }
    }
}
